import json
from pathlib import Path

import requests


BACKEND_URL = "http://127.0.0.1:8000"
# Какие уровни заданий хотим сгенерировать
LEVELS = [0, 1, 2, 3]
# Сколько задач на каждый уровень
TASKS_PER_LEVEL = 5

PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_GD_PATH = PROJECT_ROOT / "db" / "task_data.gd"


def fetch_tasks_for_level(level: int, count: int):
    url = f"{BACKEND_URL}/generate_tasks"
    payload = {"level": level, "count": count}
    resp = requests.post(url, json=payload, timeout=30)
    if resp.status_code != 200:
        print(f"  backend error status={resp.status_code} body={resp.text}")
        resp.raise_for_status()
    data = resp.json()
    tasks = data.get("tasks", [])
    # Подстрахуемся, что у каждой задачи правильный level
    for t in tasks:
        t["level"] = level
    return tasks


def to_gd_string(value):
    """Превращаем Python-значение в строку GDScript."""
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return str(value)


def build_task_data_gd(all_tasks):
    header = "# AUTOGENERATED by beck/generate_tasks_to_gd.py\n"
    header += "extends Node\n\n"
    header += "var default_tasks = [\n"

    lines = [header]

    for t in all_tasks:
        desc = str(t.get("description", ""))
        if not desc.startswith("AI:"):
            # Маркер, по которому игра будет выбирать только AI-задачи.
            # Иначе в sqlite будут оставаться старые задания, и терминал сможет
            # случайно выдавать их.
            desc = "AI: " + desc
            t["description"] = desc
        row_lines = [
            "\t{",
            f'\t\t"level": {int(t.get("level", 0))},',
            f'\t\t"category": {to_gd_string(t.get("category", ""))},',
            f'\t\t"description": {to_gd_string(t.get("description", ""))},',
            f'\t\t"expected_output": {to_gd_string(t.get("expected_output", ""))},',
            f'\t\t"required_patterns": {to_gd_string(t.get("required_patterns", ""))},',
            f'\t\t"check_type": {to_gd_string(t.get("check_type", "stdout_exact"))},',
            f'\t\t"required_keywords": {to_gd_string(t.get("required_keywords", ""))},',
            f'\t\t"allow_direct_print": {int(t.get("allow_direct_print", 0))},',
            "\t},",
        ]
        lines.append("\n".join(row_lines) + "\n")

    lines.append("]\n")
    return "".join(lines)


def main():
    all_tasks = []

    for lvl in LEVELS:
        print(f"Fetching tasks for level {lvl} from backend...")
        try:
            tasks = fetch_tasks_for_level(lvl, TASKS_PER_LEVEL)
        except Exception as e:
            print(f"  ERROR: cannot fetch tasks for level {lvl}: {e}")
            continue
        all_tasks.extend(tasks)

    if not all_tasks:
        print("No tasks fetched from backend, abort.")
        return

    gd_text = build_task_data_gd(all_tasks)

    OUTPUT_GD_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_GD_PATH.write_text(gd_text, encoding="utf-8")
    print(f"Wrote {len(all_tasks)} tasks to {OUTPUT_GD_PATH}")


if __name__ == "__main__":
    main()

