import json
from pathlib import Path
import re

import requests

from tasks_fallback_catalog import catalog_tasks_for_level


BACKEND_URL = "http://127.0.0.1:8000"
# Какие уровни заданий хотим сгенерировать
LEVELS = [0, 1, 2, 3]
# Сколько задач на каждый уровень
TASKS_PER_LEVEL = 5
# Сколько дополнительных попыток на уровень, если пришёл fallback/мало задач
MAX_LEVEL_RETRIES = 5

PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_GD_PATH = PROJECT_ROOT / "db" / "task_data.gd"


def fetch_tasks_multi(levels: list[int], count: int):
    """Один запрос /generate_tasks_multi (быстрее, чем N вызовов /generate_tasks)."""
    url = f"{BACKEND_URL}/generate_tasks_multi"
    payload = {"levels": levels, "count_per_level": count}
    last_err: Exception | None = None
    for attempt in range(1, 3):
        try:
            resp = requests.post(url, json=payload, timeout=420)
            if resp.status_code == 404:
                raise RuntimeError("no_multi_endpoint")
            if resp.status_code != 200:
                print(f"  backend error status={resp.status_code} body={resp.text}")
                resp.raise_for_status()
            data = resp.json()
            source = data.get("source", "")
            tasks = data.get("tasks", [])
            if source:
                print(f"    source={source}")
            return tasks, str(source or "")
        except Exception as e:
            last_err = e
            print(f"  multi attempt {attempt}/2 failed: {e}")
    if last_err:
        raise last_err
    return [], ""


def fetch_tasks_for_level(level: int, count: int):
    """Получаем задачи для конкретного уровня из backend.

    Возвращает: (tasks, source), где `source` — строка с причиной/откуда взялось
    содержимое (например, "fallback").
    """
    url = f"{BACKEND_URL}/generate_tasks"
    payload = {"level": level, "count": count}
    # Ollama может отвечать дольше 30 секунд (особенно первый раз при прогреве/скачивании).
    # Делаем пару попыток с большим таймаутом.
    last_err: Exception | None = None
    for attempt in range(1, 3):
        try:
            resp = requests.post(url, json=payload, timeout=180)
            if resp.status_code != 200:
                print(f"  backend error status={resp.status_code} body={resp.text}")
                resp.raise_for_status()
            data = resp.json()
            source = data.get("source", "")
            tasks = data.get("tasks", [])
            if source:
                print(f"    source={source}")
            for t in tasks:
                t["level"] = level
            return tasks, str(source or "")
        except Exception as e:
            last_err = e
            print(f"  attempt {attempt}/2 failed: {e}")
    if last_err:
        raise last_err


def to_gd_string(value):
    """Превращаем Python-значение в строку GDScript."""
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return str(value)


def _catalog_tasks_flat() -> list[dict]:
    rows: list[dict] = []
    for lvl in LEVELS:
        for obj in catalog_tasks_for_level(lvl, TASKS_PER_LEVEL):
            row = dict(obj)
            row["level"] = lvl
            rows.append(row)
    return rows


def build_task_data_gd(all_tasks):
    """Собираем все полученные задачи в GDScript-строку для `db/task_data.gd`.

    Плюс нормализуем формулировки описаний там, где модель "хардкодит" имя
    переменной вместо ожидаемого значения.
    """
    header = "# AUTOGENERATED by beck/generate_tasks_to_gd.py\n"
    header += "extends Node\n\n"
    header += "var default_tasks = [\n"

    lines = [header]

    def _rewrite_fixed_var_description(desc: str, expected_output: str) -> str:
        """
        Подчищаем формулировки, где AI/фоллбек хардкодит имя переменной.
        Нам важно, чтобы человек понимал: имя переменной может быть любым,
        главное - вывести ожидаемое значение.
        """
        # Если ожидаемое — многострочное, лучше не трогать.
        if expected_output is None:
            return desc
        expected_output = str(expected_output).replace("\r", "")
        if "\n" in expected_output:
            return desc

        val = re.escape(expected_output)

        # Примеры, которые хотим нормализовать:
        # "Создай переменную name = "Python" и выведи её"
        # "Создай переменную age = 20 и выведи её"
        # "Присвойте переменной x значение "Python" и выведите её"
        patterns = [
            rf'(Создай\s+переменную)\s+\w+\s*=\s*["\']{val}["\']\s+и\s+выведи\s+е[ёе]',
            rf'(Создай\s+переменную)\s+\w+\s*=\s*{val}\s+и\s+выведи\s+е[ёе]',
            rf'(Присвой(?:те)?\s+переменной)\s+\w+\s+значение\s*["\']{val}["\']\s+и\s+выведите\s+е[ёе]',
            rf'(Присвой(?:те)?\s+переменной)\s+\w+\s+значение\s*{val}\s+и\s+выведите\s+е[ёе]',
        ]

        for pat in patterns:
            if re.search(pat, desc, flags=re.IGNORECASE):
                # Универсальная формулировка: имя переменной не важно.
                return f'Создай переменную со значением "{expected_output}" и выведи её.'

        # Ещё один частый вариант от LLM:
        # "Создай переменную и выведи её (например name = \"Python\")"
        # Тут переменная явно задана только как пример — мы убираем привязку.
        if ("например" in desc.lower() or "example" in desc.lower()) and expected_output in desc:
            return f'Создай переменную со значением "{expected_output}" и выведи её.'

        return desc

    for t in all_tasks:
        desc = str(t.get("description", ""))
        expected_output = str(t.get("expected_output", ""))
        desc = _rewrite_fixed_var_description(desc, expected_output)
        if not desc.startswith("AI:"):
            # Маркер, по которому игра будет выбирать только AI-задачи.
            # Иначе в sqlite будут оставаться старые задания, и терминал сможет
            # случайно выдавать их.
            desc = "AI: " + desc
            t["description"] = desc
        row_lines = [
            "\t{",
            f'\t\t"level": {int(t.get("level", 0))},',
            f'\t\t"category": {to_gd_string(t.get("category", ""))},',
            f'\t\t"description": {to_gd_string(t.get("description", ""))},',
            f'\t\t"expected_output": {to_gd_string(t.get("expected_output", ""))},',
            f'\t\t"required_patterns": {to_gd_string(t.get("required_patterns", ""))},',
            f'\t\t"check_type": {to_gd_string(t.get("check_type", "stdout_exact"))},',
            f'\t\t"required_keywords": {to_gd_string(t.get("required_keywords", ""))},',
            f'\t\t"allow_direct_print": {int(t.get("allow_direct_print", 0))},',
            "\t},",
        ]
        lines.append("\n".join(row_lines) + "\n")

    lines.append("]\n")
    return "".join(lines)


def main():
    """Точка входа: генерируем набор AI-задач по уровням и сохраняем в .gd."""
    all_tasks = []
    ai_levels = 0
    per_level_ok = {}

    try:
        print("Fetching all levels via /generate_tasks_multi …")
        multi_tasks, multi_src = fetch_tasks_multi(LEVELS, TASKS_PER_LEVEL)
        target_total = len(LEVELS) * TASKS_PER_LEVEL
        if multi_src == "fallback":
            multi_tasks = _catalog_tasks_flat()
            multi_src = "catalog_fallback"
        if len(multi_tasks) == target_total:
            gd_text = build_task_data_gd(multi_tasks)
            OUTPUT_GD_PATH.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT_GD_PATH.write_text(gd_text, encoding="utf-8")
            print(
                f"Wrote {len(multi_tasks)} AI tasks to {OUTPUT_GD_PATH} "
                f"(one-shot source={multi_src})"
            )
            return
        print(
            f"  multi incomplete or fallback (got {len(multi_tasks)}/{target_total}, "
            f"src={multi_src!r}), falling back to per-level fetch…"
        )
    except Exception as e:
        print(f"  /generate_tasks_multi unavailable: {e}")

    for lvl in LEVELS:
        print(f"Fetching tasks for level {lvl} from backend...")
        level_tasks = []
        seen_desc = set()
        level_source = ""
        for attempt in range(1, MAX_LEVEL_RETRIES + 1):
            try:
                tasks, source = fetch_tasks_for_level(lvl, TASKS_PER_LEVEL)
            except Exception as e:
                print(f"  level {lvl} attempt {attempt}/{MAX_LEVEL_RETRIES}: error: {e}")
                continue

            level_source = source
            if source == "fallback":
                print(f"  level {lvl}: server fallback → canonical catalog")
                level_tasks = []
                for obj in catalog_tasks_for_level(lvl, TASKS_PER_LEVEL):
                    row = dict(obj)
                    row["level"] = lvl
                    level_tasks.append(row)
                break

            # Накапливаем задачи между попытками и убираем дубликаты.
            for t in tasks:
                desc = str(t.get("description", "")).strip()
                if not desc or desc in seen_desc:
                    continue
                level_tasks.append(t)
                seen_desc.add(desc)
                if len(level_tasks) >= TASKS_PER_LEVEL:
                    break

            if len(level_tasks) >= TASKS_PER_LEVEL:
                level_tasks = level_tasks[:TASKS_PER_LEVEL]
                break

            print(
                f"  level {lvl} attempt {attempt}/{MAX_LEVEL_RETRIES}: "
                f"accumulated {len(level_tasks)}/{TASKS_PER_LEVEL}, retrying..."
            )

        if level_tasks:
            per_level_ok[lvl] = True
            ai_levels += 1
            all_tasks.extend(level_tasks)
        else:
            per_level_ok[lvl] = False
            print(
                f"  level {lvl}: failed to get {TASKS_PER_LEVEL} AI tasks "
                f"(last source={level_source or 'n/a'})"
            )

    target_total = len(LEVELS) * TASKS_PER_LEVEL
    if len(all_tasks) != target_total:
        print(
            "Generation incomplete: "
            f"got {len(all_tasks)}/{target_total} AI tasks. "
            f"Per-level success: {per_level_ok}. "
            "Using canonical fallback catalog instead."
        )
        all_tasks = _catalog_tasks_flat()

    gd_text = build_task_data_gd(all_tasks)

    OUTPUT_GD_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_GD_PATH.write_text(gd_text, encoding="utf-8")
    print(
        f"Wrote {len(all_tasks)} AI tasks to {OUTPUT_GD_PATH} "
        f"(levels={ai_levels}/{len(LEVELS)})"
    )


if __name__ == "__main__":
    main()

