# Синхронизировано с beck/tasks_fallback_catalog.py
# Не править вручную: python beck/sync_task_data_gd.py
# Совпадает с server source=fallback и локальным fallback Godot.
extends Node

var default_tasks = [
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Выведи строку \"Hello, World!\"",
		"expected_output": "Hello, World!",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 1,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Создай переменную со значением \"Python\" и выведи её",
		"expected_output": "Python",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 1,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Создай переменную со значением 20 и выведи её",
		"expected_output": "20",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 1,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Сложи числа 2 и 3 и выведи результат",
		"expected_output": "5",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 1,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Выведи результат выражения 7*8",
		"expected_output": "56",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 1,
	},
	{
		"level": 1,
		"category": "medium",
		"description": "AI: Создай переменную x = 12. Если x больше 10, выведи \"Большое\", иначе \"Маленькое\"",
		"expected_output": "Большое",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "medium",
		"description": "AI: Создай переменную x = 7. Если число чётное — выведи \"Even\", иначе \"Odd\"",
		"expected_output": "Odd",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "medium",
		"description": "AI: Создай строку s = \"Python\". Если строка равна \"Python\", выведи \"Да\", иначе \"Нет\"",
		"expected_output": "Да",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "medium",
		"description": "AI: Создай переменную x = -5. Если число отрицательное — выведи \"Минус\", иначе \"Плюс\"",
		"expected_output": "Минус",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "medium",
		"description": "AI: Создай переменную x = 9. Если число делится на 3 — выведи \"Div3\", иначе \"No\"",
		"expected_output": "Div3",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Пройди по списку чисел [1,2,3] и выведи каждое",
		"expected_output": "1
2
3",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Посчитай сумму чисел от 1 до 5 с помощью цикла",
		"expected_output": "15",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Выведи квадраты чисел от 1 до 3",
		"expected_output": "1
4
9",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Выведи все элементы списка ['a','b','c']",
		"expected_output": "a
b
c",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Посчитай количество элементов в списке [10,20,30]",
		"expected_output": "3",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Отсортируй список [5,2,9,1] и выведи результат",
		"expected_output": "[1, 2, 5, 9]",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Выведи только чётные числа из списка [1,2,3,4,5]",
		"expected_output": "2
4",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Найди максимальное число в списке [3,7,2]",
		"expected_output": "7",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Найди минимальное число в списке [3,7,2]",
		"expected_output": "2",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Посчитай сумму элементов списка [1,2,3,4]",
		"expected_output": "10",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
]
