# AUTOGENERATED by beck/generate_tasks_to_gd.py
extends Node

var default_tasks = [
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Напишите программу, которая выведет на экран текущую дату.",
		"expected_output": "2023-10-05
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Создайте переменную и присвойте ей значение 42, затем выведите её на экран.",
		"expected_output": "42
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Напишите программу, которая выведет на экран 'Привет, мир!' без кавычек и пробелов между словами.",
		"expected_output": "'Привет,мир'
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Создайте список из чисел от 1 до 5 и выведите его на экран в виде '1 2 3 4 5'.",
		"expected_output": "1 2 3 4 5
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 0,
		"category": "easy",
		"description": "AI: Создайте словарь с ключами 'name' и 'age', присвойте им значения 'Alice' и 30 соответственно, затем выведите его на экран в формате 'Имя: Alice, Возраст: 30'.",
		"expected_output": "Имя: Alice, Возраст: 30
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "easy",
		"description": "AI: Создайте программу, которая выведет текущую дату и время.",
		"expected_output": "2023-10-05T14:30:00
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "easy",
		"description": "AI: Создайте программу, которая выведет строку 'Привет, мир!' без использования пробелов.",
		"expected_output": "Привет,мир!
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "easy",
		"description": "AI: Создайте программу, которая выведет числа от 0 до 9 в одну строку через запятую.",
		"expected_output": "0,1,2,3,4,5,6,7,8,9
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "easy",
		"description": "AI: Создайте программу, которая выведет строку 'Привет' три раза.",
		"expected_output": "Привет
Привет
Привет
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 1,
		"category": "easy",
		"description": "AI: Создайте программу, которая выведет числа от 5 до 0 в порядке убывания.",
		"expected_output": "5
4
3
2
1
0
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Создайте программу, которая выведет на экран текущую дату и время.",
		"expected_output": "текущая дата и время
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Напишите код, который суммирует числа от 1 до 5 и выводит результат.",
		"expected_output": "6
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Создайте функцию, которая принимает два числа и возвращает их произведение.",
		"expected_output": "произведение двух чисел
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Напишите программу, которая определяет, является ли число четным или нечетным и выводит соответствующее сообщение.",
		"expected_output": "число четное
число нечетное
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 2,
		"category": "medium",
		"description": "AI: Создайте функцию, которая принимает строку и возвращает ее длину без учета пробелов.",
		"expected_output": "длина строки
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "medium",
		"description": "AI: Напишите программу, которая выведет на экран текущую дату и время.",
		"expected_output": "2023-10-05 14:30:00
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Создайте функцию, которая принимает список чисел и возвращает сумму всех элементов этого списка.",
		"expected_output": "sum = 27
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "easy",
		"description": "AI: Напишите программу, которая выведет на экран 'Привет, Мир!' без использования пробелов и кавычек.",
		"expected_output": "\"Привет,Мир!\"
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "medium",
		"description": "AI: Создайте функцию, которая принимает строку и возвращает ее длину без использования len().",
		"expected_output": "Длина строки: 14
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
	{
		"level": 3,
		"category": "hard",
		"description": "AI: Напишите программу, которая выведет на экран таблицу умножения для чисел от 1 до 9.",
		"expected_output": "1 * 1 = 1
1 * 2 = 2
...
9 * 8 = 72
9 * 9 = 81
",
		"required_patterns": "",
		"check_type": "stdout_exact",
		"required_keywords": "",
		"allow_direct_print": 0,
	},
]
